#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../providers/console'
require_relative '../providers/datadog'

require_relative '../engines/git/extractor'
require_relative '../engines/npm/extractor'
require_relative '../engines/semgrep/extractor'
require_relative '../engines/rubocop/extractor'

provider = Providers::Console.new

Engines::Git::Extractor.new.call(provider)
Engines::Npm::Extractor.new.call(provider)
Engines::Semgrep::Extractor.new.call(provider)
Engines::Rubocop::Extractor.new.call(provider)

provider.send

# NOTE: Datadog
# provider = Providers::Datadog.new('myproject.code.')

# Engines::Git::Extractor.new.call(provider)
# Engines::Npm::Extractor.new.call(provider)

# provider.send
