#!/usr/bin/env ruby
# frozen_string_literal: true

require './providers/console'

require './engines/git/extractor'
require './engines/npm/extractor'

provider = Providers::Console.new

Engines::Git::Extractor.new.call(provider)
Engines::Npm::Extractor.new.call(provider)

provider.send
